### ISSUE TITLE
jsx、tsx中引入React问题

### ISSUE THREAD

**Issue by erchuanliu** [eyea/afu-eslint-rule#13]
在jsx、tsx中引入了React，但是没有使用，Eslint规则会报错，如果不引入项目运行会报错，希望修改React引入规则

**Comment by eyea** [comment]
[已完成，详见](https://github.com/eyea/afu-eslint-rule/commit/5ee1263598b809f49785bbe41b673f5838f6923b)
在 [@afuteam/eslint-plugin-fe/v/2.0.9](https://www.npmjs.com/package/@afuteam/eslint-plugin-fe/v/2.0.9) 已处理。
